<a href="https://colab.research.google.com/github/Shubhamsagar1982/PYTHON-AND-DATA-SCIENCE-BOOTCAMP/blob/main/datascience_and_pythin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hii")

In [5]:
import numpy as np


In [18]:
arr1= np.array([1,2,3,4])

In [19]:
arr1

array([1, 2, 3, 4])

In [17]:
arr2= np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [20]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [21]:
arr2.ndim

2

In [10]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [11]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr3.ndim

3

In [13]:
#indexing in arrays
#indexing starts from 0

In [22]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [23]:
arr2[1][0]

1

In [24]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
arr3[1]

array([[5, 6],
       [7, 8]])

In [27]:
arr3[1][0]

array([5, 6])

In [28]:
arr3[1][0][1]

6

In [29]:
#iteration

In [30]:
array1=np.array([1,2,4,3,5])

In [31]:
array1

array([1, 2, 4, 3, 5])

In [32]:
array1.ndim

1

In [33]:
for i in array1:
  print(i)

1
2
4
3
5


In [34]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [35]:
for i in arr2:
  print(i)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [36]:
for i in arr2:
  for j in i:
    print(j)

1
2
3
4
1
2
3
4
1
2
3
4


In [39]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
for i in arr3:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8


In [40]:
for i in arr3:
  for j in i:
    print(j)

[1 2]
[3 4]
[5 6]
[7 8]


In [41]:
#iteration using numpy
for i in np.nditer(arr2):
  print(i)

1
2
3
4
1
2
3
4
1
2
3
4


In [55]:
arr_3= np.array([[[12,2],[52,6],[5,4]],[[99,10],[77,8],[1,0]]])

In [56]:
arr_3

array([[[12,  2],
        [52,  6],
        [ 5,  4]],

       [[99, 10],
        [77,  8],
        [ 1,  0]]])

In [57]:
arr_3.ndim

3

In [58]:
print(np.sort(arr_3))

[[[ 2 12]
  [ 6 52]
  [ 4  5]]

 [[10 99]
  [ 8 77]
  [ 0  1]]]


In [59]:
x=np.where(arr_3==52)
print(x)

(array([0]), array([1]), array([0]))


In [60]:
x=np.where(arr_3%2==0)
print(x)

(array([0, 0, 0, 0, 0, 1, 1, 1]), array([0, 0, 1, 1, 2, 0, 1, 2]), array([0, 1, 0, 1, 1, 1, 1, 1]))
